In [1]:
#Initializing libraries
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import random as r
import networkx as nx
import scipy.sparse as sp
from collections import defaultdict
from tkinter import *

In [2]:
vert = 100
edge = 200
array=np.zeros([vert, vert])
raspr=edge/(vert*vert)*2

In [3]:
#adjacency matrix creation
while edge > 0:
    for i in range(1, vert):
        for j in range(i+1, vert):
            r_raspr = r.random()
            randedge=r.randint(0,1)
            if (r_raspr <= raspr and edge > 0 and array[i,j] == 0):
                array[i,j] = randedge
                array[j,i] = randedge
                edge = edge-randedge
print (array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
#Converting an adjacency matrix to an adjacency list
adjac = defaultdict(list)
edges = set()
for i, v in enumerate(array, 1):
    for j, u in enumerate(v, 1):
        if u != 0 and frozenset([i, j]) not in edges:
            edges.add(frozenset([i, j]))
            adjac[i].append(j)
print (adjac)

defaultdict(<class 'list'>, {2: [4, 20, 42, 45, 49, 54, 89, 95], 3: [19, 20, 25, 35, 86], 4: [6, 20, 27, 34, 54, 60, 69, 76], 5: [14, 29, 39, 54, 58, 92], 6: [49, 73, 89, 93, 100], 7: [16, 38, 55, 96], 8: [69, 84, 89, 92, 97], 9: [18, 62, 70, 91], 10: [56, 66, 95, 99], 11: [93], 12: [26, 60, 74], 13: [41], 15: [42, 50, 91], 16: [47], 17: [22, 47, 55, 59, 78], 18: [65, 81, 93], 19: [48, 69], 20: [55, 62], 21: [49, 56, 61, 79, 99], 22: [99], 23: [50, 62, 70, 94], 24: [25, 65], 25: [32, 54, 70], 27: [48, 65, 96], 28: [33, 52, 57], 29: [47, 61, 71], 30: [77, 86], 31: [38, 60], 32: [46, 47, 51, 52, 63], 33: [59, 68, 69, 88, 91], 34: [42, 59, 76, 79], 35: [42, 53, 80, 85], 36: [42, 67, 83], 37: [45, 72, 83], 38: [80, 84], 39: [74], 40: [59], 41: [67, 72, 74, 95], 42: [60, 72, 83], 43: [66], 44: [60, 71, 75, 97], 45: [51, 66], 46: [55], 47: [82, 90, 95], 49: [66, 85], 50: [67, 92], 51: [78, 82, 94, 97], 52: [79, 91], 53: [67], 54: [65, 71, 73, 76], 55: [66], 56: [86], 58: [63, 75], 59: [70, 7

In [5]:
#graph parameters initialization
def get_matrix_triad(coo_matrix , data=False):
	if not sp.isspmatrix_coo(coo_matrix):
		coo_matrix = sp.coo_matrix(coo_matrix)
	temp = np.vstack((coo_matrix.row , coo_matrix.col , coo_matrix.data)).transpose()
	return temp.tolist()
edags = get_matrix_triad(array)

In [6]:
#graph initialization
G = nx.Graph()
H = nx.path_graph(array.shape[0])
G.add_nodes_from(H)
G.add_weighted_edges_from(edags)
colors = np.arange(array.shape[0])

In [7]:
#DFS alghoritm
visited1 = set()
list = []
def dfs(visited1, graph, node):
    if node not in visited1:
        list.append(node)
        visited1.add(node)
        for neighbour in graph[node]:
            dfs(visited1, graph, neighbour)

In [8]:
#BFS algorithm + shortest way search algorithm
visited2 = []
queue = [] 
list2 = []
i = 0
j = 0
def bfs(visited2, graph, node, final):
    #node is the start position, final is the finall position
    visited2.append(node)
    queue.append(node)
    k = 0
    m = 0
    while queue and m != final:
        global i, j
        #in result "j-i" counts the number of BFS layers
        i += k
        j += 1
        k = 0
        m = queue.pop(0) 
        list2.append(m)
        for neighbour in graph[m]:
            if neighbour not in visited2:
                visited2.append(neighbour)
                queue.append(neighbour)
                #k counts if there is neighbours 
                k = 1

In [9]:
#buttons functions
def button1():
    matplotlib.use('TkAgg')
    plt.figure(figsize=(20,10))
    fig = nx.draw(G,pos=nx.circular_layout(G),node_color=colors, node_size = 300, label='Generated graph')
    canvas = matplotlib.backends.backend_tkagg.FigureCanvasTkAgg(fig, master=root)
    plt.show()
def button2():
    b=r.randint(1,100)
    dfs(visited1, adjac, b)
    print('DFS result: ' + str(list))
    c=r.randint(1,len(list))
    d=list[c]
    bfs(visited2, adjac, b, d) 
    print('The way from '+ str(b) + ' to ' + str(d))
    print('BFS result: '+ str(list2))
    print('The number of interations during the shortest way: ' + str(j-i))

In [11]:
#GUI
root = Tk()
root.title("Choose an excercise")
root.geometry("300x100")

#buttons
btn1 = Button(text="I exercise. Graph generation", background="#555", foreground="#ccc",
            padx="20", pady="8", font="16", command=button1)
btn1.place(relx=.2, rely=.1, anchor="c", height=30, width=130, bordermode=OUTSIDE)
btn1.pack(fill=BOTH)
btn2 = Button(text="II exercise. Shortest path search", background="#555", foreground="#ccc",
            padx="20", pady="8", font="16", command=button2)
btn2.place(relx=.2, rely=.2, anchor="c", height=30, width=130, bordermode=OUTSIDE)
btn2.pack(fill=BOTH)

root.mainloop()

DFS result: [44, 60, 64, 70, 74, 89, 100, 71, 97, 99, 75, 94, 84, 91]
The way from 84 to 75
BFS result: [44, 60, 71, 75, 97, 64, 99, 94, 70, 74, 89, 100, 84, 91]
The number of interations during the shortest way: 7
